### ISSUE TITLE
questions about structure

### ISSUE THREAD

**Issue by wafis** [IAmTurbanMan/timerGame#2]
https://github.com/IAmTurbanMan/timerGame/blob/da4951d9304c491858d38633a2d74259536a9c94/timerGame.py#L55

perhaps there is a way to handle all of these if statements into one block of code instead of having an if case for every input 

https://github.com/IAmTurbanMan/timerGame/blob/da4951d9304c491858d38633a2d74259536a9c94/timerGame.py#L39

is there a case where this doesn't run ?

**Comment by IAmTurbanMan** [comment]
When selection == 6 it writes the globalHighScores list to a text file and then breaks the loop.
